Update forest.py
Here is an error shows about Type Error:__init__() got an unexpected keyword argument 'estimator', When install the merged one. 
"estimator" is added at forest.py, where estimator=HonestTreeClassifier(), which replaces the base_estimator in pervious version. Solved now by checking code of"sklearn.ensemble._forest" and changing back to base_estimator.